<?php

namespace Database\Seeders;

use App\Models\Theme;
use Illuminate\Database\Seeder;

class ThemeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $themes = [
            [
                'name' => 'IEHC Professional',
                'slug' => 'iehc-professional',
                'description' => 'Official IEHC theme with professional blue and gold accents',
                'colors' => [
                    'primary' => '#1e40af',
                    'primary_dark' => '#1e3a8a',
                    'primary_light' => '#3b82f6',
                    'secondary' => '#f59e0b',
                    'secondary_dark' => '#d97706',
                    'secondary_light' => '#fbbf24',
                    'accent' => '#059669',
                    'accent_dark' => '#047857',
                    'accent_light' => '#10b981',
                    'background' => '#ffffff',
                    'surface' => '#f8fafc',
                    'text_primary' => '#1e293b',
                    'text_secondary' => '#64748b',
                    'border' => '#e2e8f0',
                    'success' => '#059669',
                    'warning' => '#f59e0b',
                    'error' => '#dc2626',
                    'info' => '#3b82f6',
                ],
                'is_active' => true,
                'is_default' => true,
                'sort_order' => 1
            ],
            [
                'name' => 'Ocean Blue',
                'slug' => 'ocean-blue',
                'description' => 'Deep ocean blue theme with calming teal accents',
                'colors' => [
                    'primary' => '#0f766e',
                    'primary_dark' => '#134e4a',
                    'primary_light' => '#14b8a6',
                    'secondary' => '#0891b2',
                    'secondary_dark' => '#0e7490',
                    'secondary_light' => '#06b6d4',
                    'accent' => '#0ea5e9',
                    'accent_dark' => '#0284c7',
                    'accent_light' => '#38bdf8',
                    'background' => '#ffffff',
                    'surface' => '#f0f9ff',
                    'text_primary' => '#0f172a',
                    'text_secondary' => '#475569',
                    'border' => '#cbd5e1',
                    'success' => '#059669',
                    'warning' => '#f59e0b',
                    'error' => '#dc2626',
                    'info' => '#0ea5e9',
                ],
                'is_active' => false,
                'is_default' => false,
                'sort_order' => 2
            ],
            [
                'name' => 'Emerald Green',
                'slug' => 'emerald-green',
                'description' => 'Fresh emerald green theme with natural earth tones',
                'colors' => [
                    'primary' => '#059669',
                    'primary_dark' => '#047857',
                    'primary_light' => '#10b981',
                    'secondary' => '#16a34a',
                    'secondary_dark' => '#15803d',
                    'secondary_light' => '#22c55e',
                    'accent' => '#84cc16',
                    'accent_dark' => '#65a30d',
                    'accent_light' => '#a3e635',
                    'background' => '#ffffff',
                    'surface' => '#f0fdf4',
                    'text_primary' => '#14532d',
                    'text_secondary' => '#365314',
                    'border' => '#bbf7d0',
                    'success' => '#059669',
                    'warning' => '#f59e0b',
                    'error' => '#dc2626',
                    'info' => '#0ea5e9',
                ],
                'is_active' => false,
                'is_default' => false,
                'sort_order' => 3
            ],
            [
                'name' => 'Royal Purple',
                'slug' => 'royal-purple',
                'description' => 'Elegant royal purple theme with sophisticated violet accents',
                'colors' => [
                    'primary' => '#7c3aed',
                    'primary_dark' => '#6d28d9',
                    'primary_light' => '#a855f7',
                    'secondary' => '#9333ea',
                    'secondary_dark' => '#7c2d12',
                    'secondary_light' => '#c084fc',
                    'accent' => '#ec4899',
                    'accent_dark' => '#db2777',
                    'accent_light' => '#f472b6',
                    'background' => '#ffffff',
                    'surface' => '#faf5ff',
                    'text_primary' => '#581c87',
                    'text_secondary' => '#6b21a8',
                    'border' => '#e9d5ff',
                    'success' => '#059669',
                    'warning' => '#f59e0b',
                    'error' => '#dc2626',
                    'info' => '#3b82f6',
                ],
                'is_active' => false,
                'is_default' => false,
                'sort_order' => 4
            ],
            [
                'name' => 'Sunset Orange',
                'slug' => 'sunset-orange',
                'description' => 'Warm sunset orange theme with vibrant coral accents',
                'colors' => [
                    'primary' => '#ea580c',
                    'primary_dark' => '#c2410c',
                    'primary_light' => '#fb923c',
                    'secondary' => '#f59e0b',
                    'secondary_dark' => '#d97706',
                    'secondary_light' => '#fbbf24',
                    'accent' => '#f97316',
                    'accent_dark' => '#ea580c',
                    'accent_light' => '#fb923c',
                    'background' => '#ffffff',
                    'surface' => '#fff7ed',
                    'text_primary' => '#7c2d12',
                    'text_secondary' => '#9a3412',
                    'border' => '#fed7aa',
                    'success' => '#059669',
                    'warning' => '#f59e0b',
                    'error' => '#dc2626',
                    'info' => '#3b82f6',
                ],
                'is_active' => false,
                'is_default' => false,
                'sort_order' => 5
            ],
            [
                'name' => 'Midnight Dark',
                'slug' => 'midnight-dark',
                'description' => 'Modern dark theme with sleek midnight blue accents',
                'colors' => [
                    'primary' => '#1e293b',
                    'primary_dark' => '#0f172a',
                    'primary_light' => '#334155',
                    'secondary' => '#475569',
                    'secondary_dark' => '#334155',
                    'secondary_light' => '#64748b',
                    'accent' => '#3b82f6',
                    'accent_dark' => '#1d4ed8',
                    'accent_light' => '#60a5fa',
                    'background' => '#0f172a',
                    'surface' => '#1e293b',
                    'text_primary' => '#f8fafc',
                    'text_secondary' => '#cbd5e1',
                    'border' => '#334155',
                    'success' => '#10b981',
                    'warning' => '#f59e0b',
                    'error' => '#ef4444',
                    'info' => '#3b82f6',
                ],
                'is_active' => false,
                'is_default' => false,
                'sort_order' => 6
            ],
            [
                'name' => 'Rose Gold',
                'slug' => 'rose-gold',
                'description' => 'Elegant rose gold theme with warm pink accents',
                'colors' => [
                    'primary' => '#be185d',
                    'primary_dark' => '#9d174d',
                    'primary_light' => '#ec4899',
                    'secondary' => '#f59e0b',
                    'secondary_dark' => '#d97706',
                    'secondary_light' => '#fbbf24',
                    'accent' => '#f97316',
                    'accent_dark' => '#ea580c',
                    'accent_light' => '#fb923c',
                    'background' => '#ffffff',
                    'surface' => '#fdf2f8',
                    'text_primary' => '#831843',
                    'text_secondary' => '#9d174d',
                    'border' => '#fce7f3',
                    'success' => '#059669',
                    'warning' => '#f59e0b',
                    'error' => '#dc2626',
                    'info' => '#3b82f6',
                ],
                'is_active' => false,
                'is_default' => false,
                'sort_order' => 7
            ],
            [
                'name' => 'Sage Green',
                'slug' => 'sage-green',
                'description' => 'Calming sage green theme with natural olive accents',
                'colors' => [
                    'primary' => '#65a30d',
                    'primary_dark' => '#4d7c0f',
                    'primary_light' => '#84cc16',
                    'secondary' => '#6b7280',
                    'secondary_dark' => '#4b5563',
                    'secondary_light' => '#9ca3af',
                    'accent' => '#059669',
                    'accent_dark' => '#047857',
                    'accent_light' => '#10b981',
                    'background' => '#ffffff',
                    'surface' => '#f7fee7',
                    'text_primary' => '#365314',
                    'text_secondary' => '#4d7c0f',
                    'border' => '#d9f99d',
                    'success' => '#059669',
                    'warning' => '#f59e0b',
                    'error' => '#dc2626',
                    'info' => '#3b82f6',
                ],
                'is_active' => false,
                'is_default' => false,
                'sort_order' => 8
            ],
            [
                'name' => 'Cobalt Blue',
                'slug' => 'cobalt-blue',
                'description' => 'Professional cobalt blue theme with crisp white accents',
                'colors' => [
                    'primary' => '#2563eb',
                    'primary_dark' => '#1d4ed8',
                    'primary_light' => '#3b82f6',
                    'secondary' => '#64748b',
                    'secondary_dark' => '#475569',
                    'secondary_light' => '#94a3b8',
                    'accent' => '#0ea5e9',
                    'accent_dark' => '#0284c7',
                    'accent_light' => '#38bdf8',
                    'background' => '#ffffff',
                    'surface' => '#eff6ff',
                    'text_primary' => '#1e293b',
                    'text_secondary' => '#475569',
                    'border' => '#dbeafe',
                    'success' => '#059669',
                    'warning' => '#f59e0b',
                    'error' => '#dc2626',
                    'info' => '#2563eb',
                ],
                'is_active' => false,
                'is_default' => false,
                'sort_order' => 9
            ],
            [
                'name' => 'Amber Warm',
                'slug' => 'amber-warm',
                'description' => 'Warm amber theme with golden yellow accents',
                'colors' => [
                    'primary' => '#d97706',
                    'primary_dark' => '#b45309',
                    'primary_light' => '#f59e0b',
                    'secondary' => '#fbbf24',
                    'secondary_dark' => '#f59e0b',
                    'secondary_light' => '#fde047',
                    'accent' => '#f97316',
                    'accent_dark' => '#ea580c',
                    'accent_light' => '#fb923c',
                    'background' => '#ffffff',
                    'surface' => '#fffbeb',
                    'text_primary' => '#78350f',
                    'text_secondary' => '#92400e',
                    'border' => '#fde68a',
                    'success' => '#059669',
                    'warning' => '#f59e0b',
                    'error' => '#dc2626',
                    'info' => '#3b82f6',
                ],
                'is_active' => false,
                'is_default' => false,
                'sort_order' => 10
            ],
        ];

        foreach ($themes as $theme) {
            Theme::updateOrCreate(
                ['slug' => $theme['slug']],
                $theme
            );
        }
    }
}
